# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Animations/ 

animations {
    enabled = yes

    bezier = smoothOut, 0.16, 1, 0.3, 1
    bezier = softOvershot, 0.13, 0.99, 0.29, 1.04

    animation = windowsIn, 1, 4, softOvershot, slide
    animation = windowsOut, 1, 4, smoothOut, slide
    animation = windowsMove, 1, 4, smoothOut

    animation = fade, 1, 4, smoothOut
    animation = border, 1, 5, smoothOut

    animation = workspacesIn, 1, 5, smoothOut, slidefade 20%
    animation = workspacesOut, 1, 5, smoothOut, slidefade 20%
}
