source = ~/.cache/wal/colors-hyprlock.conf

background {
    monitor =
    path = screenshot
    blur_passes = 3
    color = $bg
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = $color1
    inner_color = $bg
    font_color = $fg
    check_color = $color2
    fail_color = $color1
    placeholder_text = <i>Password...</i>
    position = 0, -50
    halign = center
    valign = center
    font_family = JetBrainsMono Nerd Font
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $fg
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
    font_family = JetBrainsMono Nerd Font
}

image {
    monitor =
    path = ~/.face.icon
    size = 150
    rounding = -1
    position = 0, 250
    halign = center
    valign = center
    border_size = 5
    border_color = $color1
}
