# Принудительно конвертировать HDR в SDR через tone mapping
tone-mapping=bt.2446a

# Запрет mpv переключать монитор в HDR-режим
target-colorspace-hint=no

# Отключить вычисление пиков яркости (убирает HDR-метаданные)
hdr-compute-peak=no

gpu-context=wayland
gpu-api=vulkan
