$bg     = rgba({background.strip}cc)
$fg     = rgba({foreground.strip}ff)
$color0 = rgba({color0.strip}ff)
$color1 = rgba({color1.strip}ff)
$color2 = rgba({color2.strip}ff)
$color4 = rgba({color4.strip}ff)
$color5 = rgba({color5.strip}ff)
